import { UseCase }   from '@shared/application/UseCase';
import { Result }    from '@shared/domain/Result';
import { Message }   from '../domain/Message.entity';
import { Role }      from '../../auth/domain/Role.enum';
import { ITicketRepository } from '../domain/ITicketRepository';

// ── Input ────────────────────────────────────────────────
export interface ReplyToTicketInput {
  ticketId:  string;
  body:      string;   // the reply text
  authorId:  string;   // from JWT token
  role:      Role;     // from JWT token
  isAiDraft: boolean;  // true if this reply was generated by AI
}

// ── Output ───────────────────────────────────────────────
export interface ReplyToTicketOutput {
  message: ReturnType<Message['toJSON']>;
}

// ── Use-case ─────────────────────────────────────────────
export class ReplyToTicketUseCase
  implements UseCase<Result<ReplyToTicketOutput>, ReplyToTicketInput>
{
  constructor(
    private readonly ticketRepository: ITicketRepository,
  ) {}

  async execute(input: ReplyToTicketInput): Promise<Result<ReplyToTicketOutput>> {

    // Step 1 — Find the ticket to make sure it exists
    const ticket = await this.ticketRepository.findById(input.ticketId);
    if (!ticket) {
      return Result.fail('Ticket not found');
    }

    // Step 2 — Make sure the ticket is not closed
    // Nobody can reply to a closed ticket
    if (!ticket.isOpen()) {
      return Result.fail('Cannot reply to a closed ticket');
    }

    // Step 3 — Create the message entity
    const message = Message.create({
      body:      input.body,
      isAiDraft: input.isAiDraft,
      ticketId:  input.ticketId,
      authorId:  input.authorId,
      createdAt: new Date(),
    });

    // Step 4 — Save the message
    const saved = await this.ticketRepository.saveMessage(message);

    return Result.ok({ message: saved.toJSON() });
  }
}