import { Entity } from "@shared/domain/Entity";
import { uuidv7 } from "@shared/utils/idGenerators";

// Shape of data required to construct a Message
interface MessageProps {
  body: string;
  isAiDraft: boolean; // true if generated by AI
  ticketId: string;
  authorId: string | null;
  createdAt: Date;
}

export class Message extends Entity<string> {
  private props: MessageProps;

  private constructor(props: MessageProps, id?: string) {
    super(id ?? uuidv7());
    this.props = props;
  }

  // Factory method — validates body length before creating
  static create(props: MessageProps, id?: string): Message {
    if (!props.body || props.body.trim().length === 0) {
      throw new Error("Message body cannot be empty");
    }

    if (props.body.length > 10000) {
      throw new Error("Message is too long (max 10,000 characters)");
    }

    return new Message(props, id);
  }

  // Getters
  get body(): string {
    return this.props.body;
  }
  get isAiDraft(): boolean {
    return this.props.isAiDraft;
  }
  get ticketId(): string {
    return this.props.ticketId;
  }
  get authorId(): string | null {
    return this.props.authorId;
  }
  get createdAt(): Date {
    return this.props.createdAt;
  }

  // Serialize to plain object for HTTP responses
  toJSON() {
    return {
      id: this._id,
      body: this.props.body,
      isAiDraft: this.props.isAiDraft,
      ticketId: this.props.ticketId,
      authorId: this.props.authorId,
      createdAt: this.props.createdAt,
    };
  }
}
