import { Entity } from '@shared/domain/Entity';

// A message is a single reply on a ticket
// Both clients and agents can send messages
// AI-drafted responses are also stored as messages
interface MessageProps {
  body:      string;   // the actual text content of the reply
  isAiDraft: boolean;  // true if this was generated by Gemini AI
  ticketId:  string;   // which ticket this message belongs to
  authorId:  string;   // who sent this message
  createdAt: Date;
}

export class Message extends Entity<string> {
  private props: MessageProps;

  private constructor(props: MessageProps, id?: string) {
    super(id ?? '');
    this.props = props;
  }

  // ── Factory method ───────────────────────────────────────
  static create(props: MessageProps, id?: string): Message {

    // Message body must not be empty
    if (!props.body || props.body.trim().length === 0) {
      throw new Error('Message body cannot be empty');
    }

    // Message body must not be too long
    if (props.body.length > 10000) {
      throw new Error('Message is too long (max 10,000 characters)');
    }

    return new Message(props, id);
  }

  // ── Getters ──────────────────────────────────────────────
  get body():      string  { return this.props.body; }
  get isAiDraft(): boolean { return this.props.isAiDraft; }
  get ticketId():  string  { return this.props.ticketId; }
  get authorId():  string  { return this.props.authorId; }
  get createdAt(): Date    { return this.props.createdAt; }

  // ── Serializer ───────────────────────────────────────────
  toJSON() {
    return {
      id:        this._id,
      body:      this.props.body,
      isAiDraft: this.props.isAiDraft,
      ticketId:  this.props.ticketId,
      authorId:  this.props.authorId,
      createdAt: this.props.createdAt,
    };
  }
}