"""initial

Revision ID: 1f4b0e75b56d
Revises: None
Create Date: 2026-07-23 21:27:37.562628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4b0e75b56d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'fileName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('documents', 's3Key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('documents', 'mimeType',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('documents', 'sizeBytes',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('documents_ticketId_createdAt_idx'), table_name='documents')
    op.drop_constraint(op.f('documents_ticketId_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'tickets', ['ticketId'], ['id'], ondelete='CASCADE')
    op.alter_column('invoices', 'number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('invoices', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('invoices_createdAt_idx'), table_name='invoices')
    op.drop_index(op.f('invoices_number_key'), table_name='invoices')
    op.drop_index(op.f('invoices_organizationId_idx'), table_name='invoices')
    op.create_index(op.f('ix_invoices_createdAt'), 'invoices', ['createdAt'], unique=False)
    op.create_unique_constraint(None, 'invoices', ['number'])
    op.drop_constraint(op.f('invoices_organizationId_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'organizations', ['organizationId'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('messages_authorId_idx'), table_name='messages')
    op.drop_index(op.f('messages_ticketId_createdAt_idx'), table_name='messages')
    op.drop_constraint(op.f('messages_ticketId_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_authorId_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'tickets', ['ticketId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['authorId'], ['id'], ondelete='SET NULL')
    op.alter_column('organizations', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('organizations_code_key'), table_name='organizations')
    op.drop_index(op.f('organizations_slug_key'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['code'])
    op.create_unique_constraint(None, 'organizations', ['slug'])
    op.alter_column('tickets', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tickets', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Uncategorized'::text"))
    op.alter_column('tickets', 'aiTriage',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('tickets_agentId_idx'), table_name='tickets')
    op.drop_index(op.f('tickets_clientId_idx'), table_name='tickets')
    op.drop_index(op.f('tickets_createdAt_idx'), table_name='tickets')
    op.drop_index(op.f('tickets_organizationId_idx'), table_name='tickets')
    op.create_index(op.f('ix_tickets_createdAt'), 'tickets', ['createdAt'], unique=False)
    op.drop_constraint(op.f('tickets_agentId_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_organizationId_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_clientId_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['agentId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'users', ['clientId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'organizations', ['organizationId'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'passwordHash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'firstName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'lastName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('users_email_key'), table_name='users')
    op.drop_index(op.f('users_organizationId_idx'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('users_organizationId_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organizationId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organizationId_fkey'), 'users', 'organizations', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('users_organizationId_idx'), 'users', ['organizationId'], unique=False)
    op.create_index(op.f('users_email_key'), 'users', ['email'], unique=True)
    op.alter_column('users', 'lastName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'firstName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'passwordHash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_clientId_fkey'), 'tickets', 'users', ['clientId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('tickets_organizationId_fkey'), 'tickets', 'organizations', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('tickets_agentId_fkey'), 'tickets', 'users', ['agentId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_tickets_createdAt'), table_name='tickets')
    op.create_index(op.f('tickets_organizationId_idx'), 'tickets', ['organizationId'], unique=False)
    op.create_index(op.f('tickets_createdAt_idx'), 'tickets', ['createdAt'], unique=False)
    op.create_index(op.f('tickets_clientId_idx'), 'tickets', ['clientId'], unique=False)
    op.create_index(op.f('tickets_agentId_idx'), 'tickets', ['agentId'], unique=False)
    op.alter_column('tickets', 'aiTriage',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tickets', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Uncategorized'::text"))
    op.alter_column('tickets', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('organizations_slug_key'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('organizations_code_key'), 'organizations', ['code'], unique=True)
    op.alter_column('organizations', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('organizations', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_authorId_fkey'), 'messages', 'users', ['authorId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('messages_ticketId_fkey'), 'messages', 'tickets', ['ticketId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('messages_ticketId_createdAt_idx'), 'messages', ['ticketId', 'createdAt'], unique=False)
    op.create_index(op.f('messages_authorId_idx'), 'messages', ['authorId'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_organizationId_fkey'), 'invoices', 'organizations', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_createdAt'), table_name='invoices')
    op.create_index(op.f('invoices_organizationId_idx'), 'invoices', ['organizationId'], unique=False)
    op.create_index(op.f('invoices_number_key'), 'invoices', ['number'], unique=True)
    op.create_index(op.f('invoices_createdAt_idx'), 'invoices', ['createdAt'], unique=False)
    op.alter_column('invoices', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('invoices', 'number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_ticketId_fkey'), 'documents', 'tickets', ['ticketId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('documents_ticketId_createdAt_idx'), 'documents', ['ticketId', 'createdAt'], unique=False)
    op.alter_column('documents', 'sizeBytes',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('documents', 'mimeType',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 's3Key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'fileName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
